stringInput = input("")
numberList = stringInput.split(" ")
a = int(numberList[0])
b = int(numberList[1])
c = int(numberList[2])
print((a + b) % c)
print(((a % c) + (b % c)) % c)
print((a * b) % c)
print(((a % c) * (b % c)) % c)